// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DropDownListDemo.Models
{
    [Table("Student")]
    public partial class Student
    {
        [Key]
        public int RollNumber { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Gender { get; set; }
        public int? Age { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string City { get; set; }


    }
}